spring:
  datasource:
    url: jdbc:mysql://1.15.141.65/group1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: group
    password: Root123@
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false